name: Code Analysis

on:
    workflow_dispatch:
    pull_request:
        branches:
            - master

        # Explicitly specify event type, for Build step to run only on merge
        # By default workflows for pull_request event trigger on [opened, synchronize, reopened]
        # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
        types:
            - opened
            - synchronize

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    codeAnalysisAndroid:
        name: Run Android Lint and Detekt Analysis
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 1

          - name: set up JDK 17
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'temurin'
              cache: 'gradle'

          #https://github.com/android-actions/setup-android
          - name: Setup Android SDK
            uses: android-actions/setup-android@v2

          # https://github.com/marketplace/actions/run-detekt-with-reviewdog
          - name: detekt
            uses: hemraj25/Detekt-Action@v1.0.0
            with:
                github_token: ${{ secrets.GH_TOKEN }}
                detekt_config: '${{ github.workspace }}/config/detekt/detekt.yml'
                detekt_baseline: '${{ github.workspace }}/config/detekt/baseline.xml'
                reviewdog_reporter: github-pr-review
                reviewdog_level: warning
                fail_on_error: true

          - name: Run lint
            run: ./gradlew lint

          - name: Archive reports for failed build
            if: failure()
            uses: actions/upload-artifact@v3
            with:
              name: reports
              path: |
                */build/reports/lint